### ISSUE TITLE
Regression in 1.0.2 breaking matches

### ISSUE THREAD

**Issue by LukeChannings** [reifiedbeans/vite-plugin-serve-static#6] opened 2024-07-30 23:18 UTC
I have an issue where no patterns are matching in `1.0.2`.

On debugging the issue I discovered that `req.url` is always `/index.html` (e.g. `curl http://localhost:4212/foo/bar.json` will have `req.url` be `/index.html`). `req.originalUrl`, however, will be `/foo/bar.json`.

I suspect that the change in injection position introduced in `1.0.2` has caused the plugin to be evaluated after redirects have mutated `req.url`.

**Comment by reifiedbeans** [comment] 2024-07-31 04:50
Hi @LukeChannings, I'm sorry to hear you're having issues.

Can you provide a minimal reproduction of the problem you're facing? I just initialized a new Vite project with the following config, and I was not able to reproduce your issue (the `test.json` file in the project root is served to the browser).

```typescript
import path from "path";
import { defineConfig } from "vite";
import serveStatic from "vite-plugin-serve-static";

const serveStaticPlugin = serveStatic([
  {
    pattern: /^\/test.json/,
    resolve: "./test.json",
  },
]);

export default defineConfig({
  plugins: [serveStaticPlugin],
});
```

**Comment by ryshtk** [comment] 2024-08-07 06:43
Hi @reifiedbeans, I encountered the same problem.

> ```javascript
>   {
>     pattern: /^\/test.json/,
>     resolve: "./test.json",
>   },
> ```
In this case vite will directly locate `test.json`, so it works as expected.
But you can reproduce the issue by accessing `/test-json` (which should also match the pattern) or by changing the rule as follows:
```javascript
  {
    pattern: /^\/test$/,
    resolve: "./test.json",
  },
```

However, I think this would be the intended behavior of vite's `htmlFallbackMiddleware` in SPA mode, so it might be appropriate to avoid this by running vite in MPA mode:
```javascript
export default defineConfig({
  appType: 'mpa',
  plugins: [serveStaticPlugin],
});
```

Any thoughts?

**Comment by reifiedbeans** [comment] 2024-08-08 04:54
Wow, I cannot believe I didn't test something like this when releasing v1.0.2. Thanks @ryshtk for the write-up.

I verified that the [`htmlFallbackMiddleware`](https://github.com/vitejs/vite/blob/fcf50c2e881356ea0d725cc563722712a2bf5695/packages/vite/src/node/server/middlewares/htmlFallback.ts#L10) is the cause of this behavior...
```
  VITE v5.3.5  ready in 86 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
  vite:resolve 2.90ms /test-json -> null +0ms
  vite:html-fallback Rewriting GET /test-json to /index.html +0ms
  vite:time 27.24ms /index.html +0ms
```

Even though folks can work around this issue by using `appType: 'mpa'`, I do consider this a bug in the implementation, since (a) I don't expect most folks to be using MPA mode, and (b) I don't want to lock folks into using MPA mode if it doesn't work with their use case.

I don't have a solid fix for this yet, but two things I want to explore are:
1. Finding a way to disable `htmlFallbackMiddleware` in the plugin (this doesn't seem feasible or necessarily desired)
2. Switching back to running this plugin before internal middlewares (i.e., before #4) and find a way to enable CORS support (may not be perfect since there may be other features that would also have to be implemented in the plugin)

If anyone has input on this, I will gladly take it. In the meantime, I need to decide whether or not to recall v1.0.2 (input on this is also welcome). Arguably, the plugin is more broken than it was before...

**Comment by reifiedbeans** [comment] 2024-08-08 06:38
Opened #7 to implement option 2 above

**Closed** 2024-08-10 09:02 UTC
Labels: bug
